-- MySQL Script generated by MySQL Workbench
-- 01/29/17 03:35:15
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema waksharp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema waksharp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `waksharp` DEFAULT CHARACTER SET utf8 ;
USE `waksharp` ;

-- -----------------------------------------------------
-- Table `waksharp`.`accounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waksharp`.`accounts` (
  `id` INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
  `username` VARCHAR(40) CHARACTER SET 'utf8' NOT NULL,
  `pseudo` VARCHAR(40) CHARACTER SET 'utf8' NOT NULL,
  `hash_password` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL,
  `session_token` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `email` VARCHAR(45) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `gm_level` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `join_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `last_login` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  `last_ip` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL DEFAULT '127.0.0.1',
  `online` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `banned` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `subscription_time` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `waksharp`.`characters`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waksharp`.`characters` (
  `guid` INT(10) UNSIGNED NOT NULL,
  `account_id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `breed` TINYINT(3) UNSIGNED NOT NULL,
  `gender` TINYINT(3) UNSIGNED NOT NULL,
  `level` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '1',
  `xp` SMALLINT(5) UNSIGNED NOT NULL,
  `skin_color` INT(11) NOT NULL,
  `hair_color` INT(11) NOT NULL,
  `pupil_color` INT(11) NOT NULL,
  `skin_color_factor` INT(10) NOT NULL,
  `hair_color_factor` INT(10) NOT NULL,
  `cloth` INT(11) NOT NULL,
  `face` INT(11) NOT NULL,
  `title` INT(11) NOT NULL,
  `position_x` INT(11) NOT NULL DEFAULT '0',
  `position_y` INT(11) NOT NULL DEFAULT '0',
  `position_z` MEDIUMINT(9) NOT NULL DEFAULT '0',
  `direction` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `instance_id` MEDIUMINT(8) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`guid`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `waksharp`.`creature_template`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waksharp`.`creature_template` (
  `id` INT(10) UNSIGNED NOT NULL,
  `name` VARCHAR(255) CHARACTER SET 'utf8' NULL DEFAULT NULL,
  `level` SMALLINT(5) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `waksharp`.`interactive_elements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waksharp`.`interactive_elements` (
  `interactive_element_id` INT(10) UNSIGNED NOT NULL,
  `script_name` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  PRIMARY KEY (`interactive_element_id`))
ENGINE = MyISAM
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `waksharp`.`ip_banned`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waksharp`.`ip_banned` (
  `ip` VARCHAR(15) CHARACTER SET 'utf8' NOT NULL,
  `ban_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `ban_reason` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL,
  `banned_by` VARCHAR(40) CHARACTER SET 'utf8' NOT NULL,
  `unban_date` TIMESTAMP NOT NULL DEFAULT '0000-00-00 00:00:00',
  PRIMARY KEY (`ip`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


-- -----------------------------------------------------
-- Table `waksharp`.`realm`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `waksharp`.`realm` (
  `id` TINYINT(3) UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(32) CHARACTER SET 'utf8' NOT NULL DEFAULT '',
  `address` VARCHAR(255) CHARACTER SET 'utf8' NOT NULL DEFAULT '127.0.0.1',
  `port` SMALLINT(5) UNSIGNED NOT NULL DEFAULT '5556',
  `version` VARCHAR(10) CHARACTER SET 'utf8' NOT NULL DEFAULT '0.00.00',
  `community` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `player_limit` INT(10) UNSIGNED NOT NULL DEFAULT '500',
  `security_access_level` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  `locked` TINYINT(3) UNSIGNED NOT NULL DEFAULT '0',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uq_name` (`name` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
